### ISSUE TITLE
cfg file not loading or ignored?

### ISSUE THREAD

**Issue by xDololow** [JekiTheMonkey/KPS#1]
So basically settings I set for keys don't save for me. "cfg" file is created and has a button section changed but for some reason, it's not being loaded.
Video: https://puu.sh/HTQbE.mp4

**Comment by Tonetfal** [comment]
How do you close it? Just by pressing Ctrl + W or somehow else?

**Comment by xDololow** [comment]
> How do you close it? Just by pressing Ctrl + W or somehow else?

Ctrl + W

**Comment by xDololow** [comment]
Ok, just moved the .exe file to another folder and it works now. That's strange. 🤔
