### ISSUE TITLE
Weird CPU Usage

### ISSUE THREAD

**Issue by reidlabb** [JekiTheMonkey/KPS#10]
![image](https://user-images.githubusercontent.com/45904911/137411081-dc9eb81d-981b-4cee-8583-65f1eb9899da.png)
its always running in the background unless i use task manager, eating up constant 25% cpu
i dont think its a bitcoin miner or anything like that because no network is being used
do you think you could try and fix this? because this is so much better than osu kps except for this

**Comment by Tonetfal** [comment]
Was it since the beginning or you changed some parameters?

**Comment by reidlabb** [comment]
Sorry for a very late response, this is using the keybinds (`,1,-,=) and the 'New White-orange' theme.
The issue has seemed to vanish, I will tell if I see the issue again.
