### ISSUE TITLE
On Linux: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by UnnamedOrange** [JekiTheMonkey/KPS#12]
I downloaded the executable from the [release page](https://github.com/JekiTheMonkey/JKPS/releases/tag/v0.10-alpha), and got:

```
./JKPS: error while loading shared libraries: libsfml-graphics.so.2.5: cannot open shared object file: No such file or directory
```

**Comment by Tonetfal** [comment]
I thought it works on Linux, apparently no one except me used it on Linux, so the issue wasn't known. You can try to download and build SFML yourself in order to make it work, though I will link it statically on next release

**Comment by UnnamedOrange** [comment]
Thank you! Btw, because of dense BSOD on Windows, I'm using Ubuntu these days.

Maybe some documents about environment configuration could be added in README.md.

**Comment by Tonetfal** [comment]
Yeah, I'll add some documentation. Btw Windows build works perfectly on Linux with Wine

**Comment by RUvlad1** [comment]
the same issue is happening this time with libsfml-graphics.so.2.6

**Comment by Tonetfal** [comment]
> the same issue is happening this time with libsfml-graphics.so.2.6
> 

The program was made on SFML 2.5. It shouldn't require any 2.6 libs
