### ISSUE TITLE
Unable to register other keys

### ISSUE THREAD

**Issue by Pennek** [JekiTheMonkey/KPS#13]
When adding new keys after pressing `Ctrl` + `>` I am unable to assign them to anything.
Here's a video of the issue I'm having: https://www.youtube.com/watch?v=iIl9qx-1tUo

I'm on Windows 10. If there's any other info you need I'd be happy to provide it

**Comment by Tonetfal** [comment]
You probably miss understood the meaning of Ctrl + '>', it is used to add **mouse button**s, not keyboard buttons. To add keyboard buttons use Ctrl + '+' instead

**Comment by Pennek** [comment]
Okay, it feels weird from a user perspective that the two are differentiated but okay. Thank you for the quick response!

**Comment by Tonetfal** [comment]
Yeah, it seems a little bit weird, though with my old knowledge I wasn't able to make single interface for both input types (mouse and keyboard are separate input devices)
