### ISSUE TITLE
Key overlay lagging in obs

### ISSUE THREAD

**Issue by MilesNaismith1** [JekiTheMonkey/KPS#17]
Some time ago key overlay started lagging for me.  I am unsure why. 
For details check out this clip:

https://www.twitch.tv/miles_naismith/clip/PreciousBovineCrowRlyTho-nRVxvi7TCCX2By2_?filter=clips&range=24hr&sort=time

It lags only when osu is in fullscreen. when i am alttabed it works well.
It used to work regardless

**Comment by Tonetfal** [comment]
Was the settings window opened while you were playing the game? If it was, that's the issue.
