### ISSUE TITLE
jkps not working when streaming osu with desktop capture in obs

### ISSUE THREAD

**Issue by abednego2002** [JekiTheMonkey/KPS#18]
uhm yep

**Comment by Tonetfal** [comment]
What OS are you using?
Did you capture the JKPS window as a game?

**Comment by abednego2002** [comment]
> What OS are you using? Did you capture the JKPS window as a game?

i use windows 11, and i tried both game and window capture. 

well it works if i run osu borderless. but my potato pc doesn't having it so if i run osu fullscreen using desktop capture jkps would just not picked up my inputs whatsoever

**Comment by Tonetfal** [comment]
I didn't really get your last sentence. Can you elaborate it, please?

You have tried both Game and Window captures, and they do not work? The JKPS probably does get the inputs, but it's the JKPS window that doesn't get rendered. You can test it by opening up JKPS, opening up osu, pressing some buttons meanwhile in osu, and check what's the total count in the program.

**Comment by abednego2002** [comment]
i tried to use JKPS on window capture and game capture. while my osu is displayed using desktop capture. but JKPS doesn't show any input if i put the osu! game on fullscreen. it works if i change fullscreen to windowed mode. but my osu will have huge lag

**Comment by Tonetfal** [comment]
Did you try to capture both osu and JKPS using Game Capture? It's the most popular way of doing it, however using Display Capture along Game Capture for JKPS should work fine.
