### ISSUE TITLE
Key "CapsLock" isn't recognized

### ISSUE THREAD

**Issue by neisehaa** [JekiTheMonkey/KPS#19]
When i try to set a key in jKPS to Caps it says "Unknown"
Any fix?

**Comment by Tonetfal** [comment]
Caps Lock cannot be used as an input key, it's a planned behavior.
The reason why is due the fact that the library used to handle inputs does not support the caps lock.

If you really want to use Caps Lock as an input key, you can re-bind the key logical value as some other key that is supported by the program, and use it instead. However, you have to figure out how to re-bind it yourself.
