### ISSUE TITLE
A couple Suggestions

### ISSUE THREAD

**Issue by xDololow** [JekiTheMonkey/KPS#2]
1. Keys and counts hide if set keys weren't pressed for X seconds. When you're in the menu or something ;3
2. Text outline.

**Comment by Tonetfal** [comment]
1) Doable, but I am not sure if it is neccesary
2) Do you mean something like this https://i.imgur.com/jbyud2w.png? The text is green and outline color is red

**Comment by xDololow** [comment]
> 2. Do you mean something like this https://i.imgur.com/jbyud2w.png? The text is green and outline color is red

yep

**Comment by Tonetfal** [comment]
Yeah, I can make this thing, it is also pretty easy
