### ISSUE TITLE
Overlay Problem

### ISSUE THREAD

**Issue by vackyton** [JekiTheMonkey/KPS#9]
So I downloaded this since it is cleaner and better then osukps but it isn't like a overlay it shrinks :(
😢

**Comment by Tonetfal** [comment]
It shouldn't shrink, probably you are shrinking it youself in OBS or whatever you are using to record your gameplay. If you show how it looks I can try to help to fix it

**Comment by vackyton** [comment]
oh i meant like not only for obs i wanted it also on my screen and obs(obs works) and i tried deskpins and it works but it has like a pin on it can make it like osukps so it is always on the screen also for me

**Comment by Tonetfal** [comment]
Can you show the way it looks? If you want a faster conversation you can DM me on Discord that is in JKPS.cfg file, it is generated in the same directory where JKPS.exe is

**Comment by vackyton** [comment]
alr when i get home Vackyton#6510 (in school)
